# Change these first
owner: digirdpllc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
environment: github-pages
  
sites:
  - name: US Node 1
    check: "tcp-ping"
    url: $US1
    port: 1022

  - name: US Node 2
    check: "tcp-ping"
    url: $US2
    port: 1022

  - name: US Node 3
    check: "tcp-ping"
    url: $US3
    port: 1022

  - name: US Node 4
    check: "tcp-ping"
    url: $US4
    port: 1022

  - name: US Node 5
    check: "tcp-ping"
    url: $US5
    port: 1022

  - name: US Node 6
    check: "tcp-ping"
    url: $US6
    port: 1022
    
  - name: US Node M
    check: "tcp-ping"
    url: $US7
    port: 1022
    
  - name: US Node S
    check: "tcp-ping"
    url: $US8
    port: 3389
    
  - name: US Node 9
    check: "tcp-ping"
    url: $US9
    port: 22
    
#   - name: US Node 7
#     check: "tcp-ping"
#     url: $US10
#     port: 1022

#  - name: Europe Node 1
#    check: "tcp-ping"
#    url: $EU1
#    port: 1022

  - name: Europe Node 2
    check: "tcp-ping"
    url: $EU2
    port: 1022

  - name: Europe Node 3
    check: "tcp-ping"
    url: $EU3
    port: 1022

  - name: Europe Node 4
    check: "tcp-ping"
    url: $EU4
    port: 1022

  - name: Europe Node 5
    check: "tcp-ping"
    url: $EU5
    port: 1022

  - name: Europe Node 6
    check: "tcp-ping"
    url: $EU6
    port: 1022

  - name: Asia Node 1
    check: "tcp-ping"
    url: $ASIA1
    port: 1022
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.digirdp.com
  # baseUrl: /your-repo-name
  name: ""
  logoUrl: https://digirdp.com/assets/img/icon.svg
  introTitle: "**DigiRDP Status - ** Real-time monitoring tool for DigiRDP's servers."
  introMessage: We make sure that our servers are always **lightning-fast** and **reliable** so that our customers can enjoy the services.
  navbar:
    - title: Status
      href: /
    - title: Contact Support
      href: https://manage.digirdp.com/submitticket.php
    - title: Go To DigiRDP
      href: https://digirdp.com/
      
  favicon: https://github.com/digirdpllc/upptime/raw/master/assets/favicon.png
  favicon-svg: https://digirdp.com/assets/img/icon.svg
  customHeadHtml: "<title>DigiRDP Status</title><script type='text/javascript'>var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();(function(){var s1=document.createElement('script'),s0=document.getElementsByTagName('script')[0];s1.async=true;s1.src='https://embed.tawk.to/5d4c52d37d27204601c9ff11/default';s1.charset='UTF-8';s1.setAttribute('crossorigin','*');s0.parentNode.insertBefore(s1,s0);})();</script><!--End of Tawk.to Script-->"
  js: "document.getElementsByClassName('logo svelte-a08hsz')[0].href = 'https://digirdp.com'"
  workflowSchedule:
    graphs: "*/5 * * * *"
    responseTime: "*/5 * * * *"
    staticSite: "*/5 * * * *"
    summary: "*/5 * * * *"
    updateTemplate: "*/5 * * * *"
    updates: "*/5 * * * *"
    uptime: "*/5 * * * *"
